server:
  port: 8083
spring:
  application:
    name: client-three-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: springcloud
    password: 123456
    publisher-confirms: true
    virtual-host: huangfl

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 6
  client:
    service-url:
      default-zone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/