server:
  port: ${EUREKA_SERVER_PORT:8761}
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
#  server:
#    enable-self-preservation: false