spring:
  application:
    name: client-two
  rabbitmq:
    host: localhost
    port: 5671
    username: springcloud
    password: 123456
    publisher-confirms: true
    # virtual-host:
eureka:
  client:
    service-url:
      default-zone: http://localhost:8071
server:
  port: 8082