server:
  port: 8081
spring:
  application:
    name: client-one-service
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456
    virtual-host: huangfl

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 6
  client:
    service-url:
      default-zone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/

logging:
  file: ../logs/client_one.log
  level:
    feign: DEBUG
    com:
      eliefly: DEBUG
