server:
  port: 8081
spring:
  application:
    name: client-one-service
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456
    virtual-host: huangfl

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 6
  client:
    service-url:
      default-zone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/