spring:
  application:
    name: client-one
  rabbitmq:
    host: localhost
    port: 5671
    username: springcloud
    password: 123456
    publisher-confirms: true
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8071/eureka/
#server:
#  port: 8081